server:
  port: 8888
logging:
  path: logs
  file: ruleEngine.log

spring:
  application:
    name: ruleEngine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///knowledge_graph?serverTimezone=GMT&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.kg.model
  mapper-locations:
    - mapper/*

neo4j:
  datasource:
    uri: bolt://127.0.0.1:7687
    username: neo4j
    password: 123456

